### PR TITLE
Add support for current Python 3.12

### LINKED ISSUE #770: Fake pathlib not working with Python 3.12-dev
With the latest Python 3.12 version the CI tests for this version fail with the traceback:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\tests\all_tests_without_extra_packages.py", line 30, in <module>
    from pyfakefs.tests.all_tests import AllTests  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\tests\all_tests.py", line 21, in <module>
    from pyfakefs.tests import (
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\tests\dynamic_patch_test.py", line 19, in <module>
    from pyfakefs import fake_filesystem_unittest
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\fake_filesystem_unittest.py", line 90, in <module>
    from pyfakefs import fake_pathlib
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\fake_pathlib.py", line 181, in <module>
    flavour = pathlib._Flavour  # type: ignore [attr-defined]
              ^^^^^^^^^^^^^^^^
AttributeError: module 'pathlib' has no attribute '_Flavour'
```

Looks like the `pathlib` implementation has changed again (it already did change substantially in 3.11). The fake pathlib has to be adapted accordingly.

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- adapt for changed pathlib implementation (removed flavour implementation)
- Windows: add patching for some os.path functions now implemented in nt instead of ntpath
- fix handling of devnull for changed OS
- add fake implementation for os.path.splitroot
- fixes #770

#### Tasks
- [x] Unit tests added that reproduce the issue or prove feature is working
- [x] Fix or feature added
- [x] Entry to release notes added
- [x] Pre-commit CI shows no errors
- [x] Unit tests passing

### CODE REVIEW

File: CHANGES.md [hunk 1]
```diff
@@ -17,6 +17,8 @@ The released versions correspond to PyPI releases.
 ### Features
 * added possibility to set a path inaccessible under Windows by using `chown()` with
   the `force_unix_mode` flag (see [#720](../../issues/720))
+* added support for changes in Python 3.12 (currently in last beta version)
```
[the remark this answers is not in the document]
Comment (mrbean-bremen) [reply CHANGES.md:20]: True, I actually meant to write "last alpha version" - thanks!
