### ISSUE TITLE
Fake pathlib not working with Python 3.12-dev

### ISSUE THREAD

**Issue by mrbean-bremen** [pytest-dev/pyfakefs#770]
With the latest Python 3.12 version the CI tests for this version fail with the traceback:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\tests\all_tests_without_extra_packages.py", line 30, in <module>
    from pyfakefs.tests.all_tests import AllTests  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\tests\all_tests.py", line 21, in <module>
    from pyfakefs.tests import (
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\tests\dynamic_patch_test.py", line 19, in <module>
    from pyfakefs import fake_filesystem_unittest
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\fake_filesystem_unittest.py", line 90, in <module>
    from pyfakefs import fake_pathlib
  File "D:\a\pyfakefs\pyfakefs\pyfakefs\fake_pathlib.py", line 181, in <module>
    flavour = pathlib._Flavour  # type: ignore [attr-defined]
              ^^^^^^^^^^^^^^^^
AttributeError: module 'pathlib' has no attribute '_Flavour'
```

Looks like the `pathlib` implementation has changed again (it already did change substantially in 3.11). The fake pathlib has to be adapted accordingly.

**Comment by mrbean-bremen** [comment]
We don't support 3.12 yet, so this is not a bug.

**Comment by mrbean-bremen** [comment]
@browniebroke - thanks! That looks like a sensible change, given that `pyfakefs` also subclasses these classes and had to go through some hoops to make it work. Should not be too big a deal to adapt...

**Comment by mrbean-bremen** [comment]
Apart from the changed `pathlib` (which I'm on the track of getting to work), there is also a change in `os.path` under Windows, that now uses some OS-specific functions for `isdir`, `isfile`, `islink` and `exists` (called `_path_isdir`, `_path_isfile` etc.), which breaks patching these functions and currently fail some tests. 
There is a also new function `os.path.splitroot` which has to be handled (apart from `isjunction` which already has some minimal implementation) in 3.12.
